// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TSSharaDDDWEB.Infraestructure.Data;

namespace TSSharaDDDWEB.Infraestructure.Migrations
{
    [DbContext(typeof(NobreakContext))]
    partial class NobreakContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TSSharaDDDWEB.ApplicationCore.Entity.Nobreak", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.Property<string>("Label");

                    b.Property<int?>("NobreakID");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UPSModel");

                    b.Property<string>("Version");

                    b.HasKey("ID");

                    b.HasIndex("NobreakID");

                    b.ToTable("Nobreak");
                });

            modelBuilder.Entity("TSSharaDDDWEB.ApplicationCore.Entity.NobreakEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Battery");

                    b.Property<DateTime>("CreationData");

                    b.Property<double>("EventReasons");

                    b.Property<double>("Frequency");

                    b.Property<double>("InputVoltage");

                    b.Property<double>("Load");

                    b.Property<int>("NobreakID");

                    b.Property<double>("OutputVoltage");

                    b.Property<double>("Temperature");

                    b.HasKey("ID");

                    b.HasIndex("NobreakID");

                    b.ToTable("NobreakEvent");
                });

            modelBuilder.Entity("TSSharaDDDWEB.ApplicationCore.Entity.Nobreak", b =>
                {
                    b.HasOne("TSSharaDDDWEB.ApplicationCore.Entity.Nobreak")
                        .WithMany("Nobreaks")
                        .HasForeignKey("NobreakID");
                });

            modelBuilder.Entity("TSSharaDDDWEB.ApplicationCore.Entity.NobreakEvent", b =>
                {
                    b.HasOne("TSSharaDDDWEB.ApplicationCore.Entity.Nobreak", "Nobreak")
                        .WithMany("NobreakEvents")
                        .HasForeignKey("NobreakID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
